### ISSUE TITLE
Добавить favicon

### ISSUE THREAD

**Issue by podivilov** [medium-isp/medium-search-engine#12]

**Comment by nxshock** [comment]
Готово: b4cf491a922d18e2494955a0343421f3ff871f6d

**Comment by podivilov** [comment]
На сайте favicon не отображается.

![](http://i.imgur.com/lHjlb4x.png)

**Comment by podivilov** [comment]
@nxshock, не тот фавикон. Он должен быть с закруглёнными краями. Возьми на medium.isp/images/favicon.png

**Comment by nxshock** [comment]
Заменил иконку: 890e1ec2b6ab302a622d54b483b12dc8680da789. В идеале бы конечно SVG версию...

**Comment by podivilov** [comment]
Никто не использует favicon с SVG.
