### ISSUE TITLE
The search bar is not all clickable

### ISSUE THREAD

**Issue by ChronosX88** [medium-isp/medium-search-engine#4]
For the search bar to become active, you need to click specifically in the center of this line. The search bar should be clickable in all places.

**Comment by user2kcd** [comment]
Main purpose of using the search engine is search all contents in the Medium network. 
No matter where did you click. 
And oh yes, you're lazy.

**Comment by ChronosX88** [comment]
no, it's called "usability".

**Comment by nxshock** [comment]
Fixed by 254696098ad394e92090dd17a1c849bcc8164ffc
