### ISSUE TITLE
Пробел после тега <img>

### ISSUE THREAD

**Issue by podivilov** [medium-isp/medium-search-engine#7]
Мне кажется, это разумнее, чем делать конструкции вида `<img></img><tag> Помощь</tag>`
Пробел после открывающего `<tag>`.

Разумнее добавить пробел после `</img>`.

**Comment by nxshock** [comment]
Пробелы - это костыль, нужно использовать отступы. Исправил в f1b6fd7ba68fc9d0275dbf9749eb557e8085e9a4.
